language: php
php:
- 7.0
- 7.1
- nightly

matrix:
  allow_failures:
  - php: nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - cd $TRAVIS_BUILD_DIR

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml